### ISSUE TITLE
Event object

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#1]
This is an object that defines an event handler, its available actions and recipient callbacks, and its UI.

An example usage is:

```php
$event = Event::register( ‘draft_to_pending’ )->add_ui( ‘A draft is ready to be published’ );
```

Protected properties:

- Events (static array)
- Listeners (array)
- Message_tags (array)
- Message_actions (array)
- Recipients_handlers (array)
- Ui (UI)
- Name (string)

Public methods:

* **static register**\
  @param $id string\
  @return Event\
  Creates a new Event object, adds it to the self::$events array and then returns the new object.\
  
* **constructor**\
  @param $id string An identifier that can be passed to WorkFlow()->when(). If no call is made to 
  `add_listener()` then assume $id is the action name.
  This method should add self to self::$events with $id as the key\
  
* **add_listener**\
  @param $action string|array|callable If it’s a string it’s assumed to be an action. Only the first param is passed to message actions or recipient handlers. If it’s an array it should follow the format: [ $action, $callback, $priority, $args_count ]. If it’s callable then it should return a non-null value to trigger the event. That value is passed to message actions and recipient handlers.
  @return self
  This method should add the value of $action to $this->handlers\
  
* **add_message_tags**\
  @param $tags array|callable Array of key/value pairs that can be substituted into the message delivered to the destinations. Can also be a function that receives the value from the event handler, must return an array\
  @return self\
  This method should merge the value of $tags into to $this->message_tags\
  
* **add_message_action**\
  @param $id string A reference name for the action\
  @param $text string The link or button text for the action\
  @param $callback_or_url string|callable If this is a callable then it will be executed when the action is clicked. Data from the event action or the result of $args if defined is passed as the 1st parameter. If the callback returns a string and it’s a URL the user is the redirected otherwise they are shown the string via wp_die(). If nothing is returned a success message is shown, if false or WP_Error is returned then the message is displayed via wp_die(). If value is a string then it assumed to be the URL for the link.\
  @param $args null|callable An optional function that receives the return value of the event action, You can do any necessary transformations of that data to prepare it for a URL here.\
  @param $schema array An array of accepted $_GET arguments and their corresponding sanitisation callback\
  @return self\
  This method should add the $text, $callback and $args parameters as an array to $this->message_actions with $id as the key\
  
* **add_recipient_handler**\
  @param $id string An identifier for the recipient handler to be used in the WorkFlow()->who() method.\
  @param $name string A nice name to be shown in the UI\
  @param $callback callable This receives the event action value as it’s 1st parameter and should return one or an array of email addresses, user objects, user IDs or user roles\
  @return self\
  This method should add the $name and $callback parameter to $this->recipient_handlers with $id as the key\
  
* **add_ui**\
  @param $ui string|UI A nice name to show in the UI or a UI object\
  @return self\
  If UI is a string pass it to new UI( $ui ) to get a UI object.\
  \
  Set the $this->ui property to the UI object.\
  It should also call $ui->set_key( ‘event_’ . $this->id ) to pass the event ID and $type ‘event’.\
  \
  If this method isn’t called and $this->name isn’t set then the event should not show in the ‘When’ section of the UI.\
  
* **get (static)**\
  @param $id string An event id\
  @return Event\
  This method should return an Event object from $this->events using $id as the key\
  
* **get_listeners**\
  @return array $this->listeners\
  
* **get_message_tags**\
  @return array $this->message_tags\
  
* **get_recipient_handler**\
  @param $id string The ID of the handler\
  @return array $this->recipient_handlers\
  
* **get_message_actions**\
  @return array $this->message_actions\
  
* **get_ui**\
  @return array $this->ui\

**Comment by pdewouters** [comment]
In the example above `->add_ui( ‘A draft is ready to be published’ );` what type of UI is that? A destination UI?
