### ISSUE TITLE
Workflow who method does not support arbitrary email addresses

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/Workflows#101]
The documentation for the `who` method in the Workflow class indicates that an email address can be passed. However, this email address has to match the email address of an existing WordPress user.

This is not clear in the documentation, making it seem like arbitrary email addresses could be passed in (which is unsupported).

Docs: https://github.com/humanmade/Workflows/wiki/Workflow#who-arrayintstringcallable-who---workflow

**Comment by jazzsequence** [comment]
Would it be worth implementing a filter to allow individual use cases that would allow arbitrary email addresses on the project-level?

**Comment by jazzsequence** [comment]
Existing docs say:

> Can be a recipient handler ID (see the Event object's add_recipient_handler method, a username, user role or email address.

I propose this is updated to: 

> Can be a recipient handler ID (see the Event object's add_recipient_handler method, a username, user role or an email address associated with a WordPress user.

**Comment by roborourke** [comment]
+1 on the docs update. I'm not sure regarding the filter though, for instance if it's for testing you could create a custom destination handler to send to a custom email address.

**Comment by jazzsequence** [comment]
It’s not just for testing that I’m thinking but after looking at the code, it seems like there would need to be too many exceptions made to allow it. Originally, Sony asked if email alerts could be sent to an internal distribution list by email. Ultimately, we built an alternate solution which included a custom recipient handler of WordPress users, but I can see similar requests from clients. In those cases, though, a custom Destination could be built, so it’s not like it’s impossible to do today.

**Comment by jazzsequence** [comment]
Updated docs: https://github.com/humanmade/Workflows/wiki/Workflow#string-1
