### ISSUE TITLE
Add error log messages to hint at incorrect usages

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#102]
There are some instances where we could provide a clearer error message when some seemingly valid input for a method is not working rather than failing completely silently.

One instance of this is passing an email address to `who()` or deriving it from a recipient handler that can't be ascribed to a WordPress user account. The data passed in must be able to map to a WP user account for it to be processed and this isn't clear in the docs at all.

There are likely other places in the code where we are checking conditions and returning early without logging some useful feedback.

This issue is a placeholder to carry out a sweep of the core classes and find places we can improve.

Props to @jazzsequence for highlighting the need for this.

**Comment by rmccue** [comment]
Closing as stale.
