### ISSUE TITLE
Document default Events

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/Workflows#110]
The `Event::remove` method is documented, but without doing a `Event::get_all()` it's not obvious what all the ids for the default events are. It would be easier for developers to have a list of default events either in the `remove` documentation or in a separate doc.

**Proposed solution**
Add the following to the Event wiki page above Public Methods:

### `draft_to_pending`
Triggered when a post is pending review.

See [`{$old_status}_to_{$new_status}`](https://developer.wordpress.org/reference/hooks/old_status_to_new_status/)

### `publish_post`
Triggered when a post is published.

See [`{$new_status}_{$post->post_type}`](https://developer.wordpress.org/reference/hooks/new_status_post-post_type/)

### `publish_page`
Triggered when a page is published.
See [`{$new_status}_{$post->post_type}`](https://developer.wordpress.org/reference/hooks/new_status_post-post_type/)

### `transition_post_status`
Triggered when a post changes status.

See [`transition_post_status`](https://developer.wordpress.org/reference/hooks/transition_post_status/)

### `published_comment`
Triggered when a new comment is published.

See [`wp_insert_comment`](http://developer.wordpress.org/reference/functions/wp_insert_comment/)

### `new_editorial_comment`
Triggered when a new editorial comment is added.

See [`wp_insert_comment`](http://developer.wordpress.org/reference/functions/wp_insert_comment/)

**Comment by jazzsequence** [comment]
Moving to review. If this looks good I can copy it into the wiki.

**Comment by roborourke** [comment]
Love it - yes please add this list, thanks again!

**Comment by jazzsequence** [comment]
Done: https://github.com/humanmade/Workflows/wiki/Event#default-events
