### ISSUE TITLE
Document default Destinations

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/Workflows#111]
The `Destination::remove` method is documented, but without doing a `Destination::get_all()` it's not obvious what all the ids for the default events are. It would be easier for developers to have a list of default events either in the `remove` documentation or in a separate doc.

**Proposed solution**
Add the following to the Destination wiki page above Public Methods:

### `dashboard`
Sends a notification to the dashboard.

### `email`
Sends an email notification.

### `slack`
Sends a notification to Slack.

**Comment by jazzsequence** [comment]
Moving to review. If this looks good I can copy it into the wiki.

**Comment by roborourke** [comment]
Yeah I think this is a good addition, thanks @jazzsequence .

**Comment by jazzsequence** [comment]
Done: https://github.com/humanmade/Workflows/wiki/Destination#default-destinations
