### ISSUE TITLE
Built in Destination: Email

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#12]
No brainer!

- [x] Sends an email to users or provided addresses, uses bcc field to only send one email

**Comment by pdewouters** [comment]
Would you set the subject programmatically or let the user define it?

**Comment by roborourke** [comment]
> Would you set the subject programmatically or let the user define it?

Good question. We could add a UI field for it, otherwise try and default to something sensible along the lines of "Notification from example.com: <Event name>"
