### ISSUE TITLE
Notifications do not seem to notify in Altis v7

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/Workflows#136]
**Steps to reproduce**
1. On Altis `local-server`...
2. Create a new workflow to notify All Users when a post is Published via Email & Dashboard
3. Publish a new post
4. No notifications are sent.

Unlike in https://github.com/humanmade/product-dev/issues/692, no errors appear in the PHP error log or in the console.

**Comment by roborourke** [comment]
Can you confirm the notification was set to "Enabled"? Just tried on my local and no issues.

![Screenshot 2021-04-06 at 17.05.02.png](https://images.zenhubusercontent.com/552cff0e4f7a08fbb7f28ce5/759c418e-4a61-4f4b-bf1b-ce7948deb27e)

**Comment by jazzsequence** [comment]
Confirmed on a clean environment with an active workflow that no notifications (dashboard or email) are sent.

**Comment by jazzsequence** [comment]
![Screen Shot 2021-04-06 at 10 40 49 AM](https://user-images.githubusercontent.com/991511/113747430-9d322e00-96c4-11eb-819e-386b455c25be.png)

**Comment by jazzsequence** [comment]
I have also reproduced this issue on Platform Test (now that humanmade/product-dev#692 is resolved).
https://platform-test.aws.hmn.md/wp-admin/post.php?post=644&action=edit

**Comment by roborourke** [comment]
@jazzsequence I had a look at the test notification and the bug seems to apply to only certain recipient types - I noticed that specific users failed but assignees did not. So delivery isn't the issue but some of the recipient handlers aren't behaving.

**Comment by jazzsequence** [comment]
I'm reproducing this locally when "assignees" is selected as who should be notified, as well.

**Comment by roborourke** [comment]
Wondering if there's some other permission level issue in play here, the only problem I could reproduce or see was with setting the specific users option.

PR up for at least on of these issues here https://github.com/humanmade/Workflows/pull/142

**Comment by jazzsequence** [comment]
I can reproduce this in one environment using Altis v7.0.0-beta1 but not in my dev environment. 

However another issue popped up in testing this. Closing this and opening a new issue.
