### ISSUE TITLE
Multiple assignees cannot be added to a post

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/Workflows#141]
When attempting to add multiple assignees to a post, only one assignee is saved. 
When adding a second assignee to a post that has an assignee, both assignees are cleared.

Steps to reproduce:
1. Create a new post. Save it as a draft.
2. Add an assignee and an editorial comment to it.
3. Add a second assignee and editorial comment to it.
4. Both assignees are lost.

![2021-04-07 at 12 10 PM](https://user-images.githubusercontent.com/991511/113914386-ba393080-979a-11eb-81c5-a069005373bb.gif)

1. Create a new post. Save it as a draft.
2. Add multiple assignees and an editorial comment to it.
3. Only one assignee is assigned.

![2021-04-07 at 12 12 PM](https://user-images.githubusercontent.com/991511/113914404-bf967b00-979a-11eb-88f4-4e4e6f26ad19.gif)

Expected behavior:
Multiple assignees can be added to a post.

**Comment by roborourke** [comment]
That's odd. I'm not able to reproduce this behaviour myself. Are there any JS errors in the console?

**Comment by jazzsequence** [comment]
hmm...odd. not able to reproduce this now. closing. ¯\_(ツ)_/¯
