### ISSUE TITLE
Adding an editorial comment with no change to assignees generates an error

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/Workflows#144]
When I attempt to leave an editorial comment on a post without changing the assignees, the message saves, but is not displayed. Instead, an error displays on the page and in the console.

This has been reproduced on both Platform Test and my local dev environment.

**Steps to reproduce:**
1. Add multiple assignees to a post
2. Set a workflow notification to notify all assignees by email and dashboard
3. Add an editorial comment to the post

![2021-04-09 at 9 36 AM](https://user-images.githubusercontent.com/991511/114206101-3a38d500-9918-11eb-81f1-9177c71aa384.gif)

**Expected behavior:**
- Comment posts with no error
- Assignees are not attempted to be reassigned when no assignees have been added

**Questions:**
- How are assignees removed? It seems you can add new assignees and _change_ assignees, but not remove existing assignees. Is there a UI element missing where assignee names appear in the Assignees dropdown box that allows you to deselect selected assignees?
![2021-04-09 at 9 48 AM](https://user-images.githubusercontent.com/991511/114206699-d662dc00-9918-11eb-97bd-30125d6ceb68.png)

**Comment by roborourke** [comment]
There's an existing issue to enable removing assignees, not sure how that will be implemented yet exactly though

 I think due to some changes to the REST API this error message is new, the comment still gets added though.

**Comment by jazzsequence** [comment]
Yes, the content still gets added, but you don't see it until you refresh. I think solving that issue is the immediate priority and we can worry about the UX changes for removing assignees later.

**Comment by jazzsequence** [comment]
Related issue for removing assignees: #94
