### ISSUE TITLE
User selection in workflows form doesn't show selected values.

### ISSUE THREAD

**Issue by shadyvb** [humanmade/Workflows#161]
### Context

If `Specific users` is selected, and a user is selected that's not within the initial list of users, the select box doesn't show the selection.

### Steps to reproduce

- Create a new workflow
- Select `Specific users` in `Who should be notified`
- In the additional box on the right, try searching for a user that is not already populated within the initial list, and select that user

### Expected
- The user is selected and is visible as a selected option within the select input.

### Actual
- The user doesn't show up as selected, unless you search for the same user again, then it'll show as selected, and then disappear again once the search text is cleared.

Reference to support request: https://humanmade.zendesk.com/agent/tickets/5649 & https://humanmade.zendesk.com/agent/tickets/6432

**Comment by mattwatsoncodes** [comment]
Came here to report the same issue, however I see a fix is in progress 👏
