### ISSUE TITLE
Enabled Workflows causing fatal error

### ISSUE THREAD

**Issue by robindevitt** [humanmade/Workflows#176]
When Workflows are enabled, create a new post of page generates a fatal error.

#### Steps to reproduce:
1. Ensure the site has a Workflow created and enabled.
2. Create a new `post` or `page`.
3. The following error is visible.
>  **Fatal error: Uncaught Error:** Unknown named parameter `$ui_data`in **/usr/src/app/vendor/humanmade/workflows/inc/class-workflow.php** on line **160**

#### Temporary fix
Disabling the enabled Workflow allows a new `post` or `page` to be created.

#### Screenshots
![Screenshot 2022-05-11 at 14.57.31.png](https://images.zenhubusercontent.com/615d863972ceea502ec6a54f/cff78e61-5330-4e8d-8e50-04f97f611210)

#### Further Details
- Altis Version - 10
- PHP Version - 8

#### Acceptance criteria:
- [x] Create a new `post` or `page` with a workflow enabled.

**Comment by robindevitt** [comment]
Looking up 
> Uncaught Error: Unknown named parameter

I cam across the following docs https://php.watch/versions/8.0/named-parameters#named-params-call_user_func_array

**Comment by roborourke** [comment]
Do you have any questions on how to fix this @robindevitt ? Looks pretty straightforward

**Comment by robindevitt** [comment]
All good thanks @roborourke , simple fix, just fought a bit to replicate the issue locally but got it sorted.
