### ISSUE TITLE
Editorial comments show in the comment count indicator badge

### ISSUE THREAD

**Issue by mikelittle** [humanmade/Workflows#194]
Editorial comments show in the comment count indicator badge. They shouldn't. The comment count routine needs to be filtered. Clicking the badge to takes you to a comment page with nothing to show.

Steps to reproduce:
1. Create a post and add some editorial comments
2. Go to the post listing and observe the comment count indicator badge shows and includes the number of editorial comments.
3. Clicking the link takes you to a comment listing page but with nothing to show

The standard comment count badge should not include editorial comments.
Some options to fix:
- Filter the comment count to exclude the editorial comments
- Add another column with a count badge for the editorial comments
- Clicking the badge should either go to a comment page of the correct type e.g  `https://altis-upgrade-test.altis.dev/wp-admin/edit-comments.php?comment_type=workflow&p=32`
- Or should go to the editorial comments section on the post editor page. and scroll down to the editorial comments meta box `#hm.workflows.editorial-comments`

![comments-notification.gif](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/c3c5f333-441b-4da8-a917-5324e241f429)

Acceptance criteria:

- [ ] ...

**Comment by robindevitt** [comment]
@mikelittle I have made some progress on this today which should be adequate for what is needed. I have the PR #195 open for it. Potentially creating a new issue for after the v12 release where we can showcase workflow comment count in it's own column would be a nice to have.

**Comment by mikelittle** [comment]
It looks like you found the right filter. 
I think adding a new column (or a second badge in the same column) would be a good feature. Perhaps raise it as a new ticket and add it to the product board for consideration.

**Comment by robindevitt** [comment]
PR has been merged
