### ISSUE TITLE
Workflow object

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#3]
This object is what we will pass configurations created in the UI to. It can also be invoked directly programmatically.

An example of the API usage might be:

```php
$wf = Workflow::register( 'draft_to_pending' )
  ->when( ‘draft_to_pending’ )
  ->what( ‘%post.post_title% is ready to publish’ )
  ->who( ‘editor’ )
  ->where( ‘email’ );
```

Protected properties:

- instances Array (static)
- event Event
- recipients Array
- messages Array
- destinations Array of Destintaions

Public methods:

* **register (static)**\
  @param $id string\
  @return Workflow
  This method should create a new Workflow object and add it to self::$instances. It should then return the object.
  
* **when (Event Listener)**\
  @param $event Event|string\
  @return self\
  If `$event` is a string that matches an event object `$id` then the get the object using `Events::get( $event )`\
  \
  If `$event` is any other string then assume this is an action and create a new Event object with `$event` as the `$id` parameter\
  \
  Set $this->event to the Event object\
  \
  Once we have an Event object do the following:
  * Loop over `$event->listeners`
    * If handler is a string or array call add_action with a lambda callback
    * If handler is a string In the lambda callback pass `func_get_args()` to `$this->run()` if not null
    * If handler is an array and has a custom `$callback` merge the value of `func_get_args()` with `$event->ui->get_data()` and call it with `call_user_func_array( $callback, $args )` and pass the return value to `$this->run()` if not null
    * If handler is a callable pass its return value to $this->run() if not null

* **what (Message builder)**\
  @param $message callable|string\
  @param $actions callable|array Optional\
  @return self\
  If `$message` is a callable the function will receive the result of the Event Listener action or callable and should return a string. Add the string to an array with the key ‘message’\
  \
  If `$message` is a string add it to an array with the key ‘message’.\
  \
  `$actions` should be an array of registered action names for the Event or arrays. It can also be a function that returns an array of arrays. Each array in the list should contain the following keys:
  * `text (string)` The text to show as the link
  * `callback_or_url (callable|string)` If this is a string then it is used as the action link value, if it is a callable then it will be executed when the action is clicked. It receives the data from the event. If it returns nothing then a success message will be displayed, if false or WP_Error a failure message is shown with the details. If a string is returned a success message and that text will be shown and if the string is a URL the user will be redirected. 
  * `args (callable|array)` An optional function that returns an array or an array of data to be appended to the action link. This lets you modify the event data for URL params
  * `schema (array)` An array of accepted keys and a sanitisation callback
  Merge `$actions` with `$this->event->get_message_actions()`\
  \
  Pass `$actions` to `$this->run_actions()`\
  \
  If `$actions` is set it should be added to the earlier array with a key of ‘actions’.\
  \
  The response array should be added to `$this->messages`
  
* **who (Recipients)**\
  @param $who array|int|string|callable\
  @return self\
  If `$who` is an array merge it with `$this->recipients` otherwise add it to the array.
  
* **where (Destinations)**\
  @param $type string|Destination|callable\
  @return self\
  Add `$type` to `$this->destinations` array if it is a string or Destination object.\
  \
  If `$type` is a callable it will receive the array of recipients and messages.

Protected methods:

* **run**\
  @param $args The return value from the callback or arguments from the action.\
  This method is invoked when the the event listener gets a non-null value.\
  \
  In sequence it does the following:
  * Parse `$this->recipients`
    * If it matches one of `$this->event->get_recipient_handler( $id )`, get the return value from the callback, passing `$args` to the callback.
    * if email try to find a matching user
    * if any other string try to find user by login
    * Failing the above then try and find users by role
  * Parse `$this->messages` by looping over each:
    * If callable get return value from callback, pass `$args` as 1st param
    * Get message tags from `$this->event->get_message_tags()`
    * Reduce tags, if callable then pass `$args` in to callback and merge result into `$carry`, if not callable add item with same key to `$carry`.
    * Array_map the array_keys to add %% around the keys
    * Pass the resulting or original string to a str_replace() function that replaces the array of keys from above and the message tags array as the values
  * For each item in `$this->destinations`
    * Filter out recipients with this destination notification disabled
    * Call `$destination->call_handler()` callback with args: `$this->recipients`, `$this->messages`\
      \
      Destinations callback will generate and send email / slack notification etc to all recipients.\
      \
      Callback will also add the actions to the message and generate an incoming URL to be used to invoke it’s callback if none provided.\
      \
      If callback returns WP_Error then pass the message to error_log()
  
* **run_actions**\
  @param $actions array\
  Parse actions, for each with a callback set and no URL provided check if we are hitting the WorkFlow incoming webhook URL.\
  \
  Required parameters are:
  * Event ID
  * Action ID
  * Valid nonce
  
  If the above criteria are satisfied then use `$schema` if set to sanitise the data and pass it to `$callback`.\
  \
  If `$schema` is not provided sanitise everything in `$_GET` with `sanitize_text_field()` before passing it to `$callback`.

**Comment by pdewouters** [comment]
So workflows would be defined as data in an options table and instantiated during WP load?

**Comment by roborourke** [comment]
> So workflows would be defined as data in an options table and instantiated during WP load?

Either the options table or as a post type & metadata. We could build a UI more quickly using a post type.
