### ISSUE TITLE
Give administrators necessary capabilities so the plugin works on single-site installs

### ISSUE THREAD

**Issue by goldenapples** [humanmade/Workflows#33]
It took me a little to while to figure out why the plugin wasn't showing any UI when I first installed it. It turned out that it was because the necessary capabilities - `edit_workflows`, `publish_workflows`, `read_workflows`, etc. - aren't granted to any users by default. Looks like the plugin is designed to work for super admins only out of the box.

It would be good to grant these caps to administrators on an activation hook, so that users installing Workflows on single-site installs can access the UI.

**Comment by roborourke** [comment]
Thanks! Can't remember the last time I ran a single site install :/

**Comment by roborourke** [comment]
Gonna add these caps for all admins, super or otherwise by default.
