### ISSUE TITLE
Network Admin UI & Workflow Capabilities

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#34]
Workflows should have a network admin level UI for network level flows.

As part of this when the constituent parts of a workflow are created eg. `Event`, `Recipient`, `Destination` etc it should be possible to assign a capability to that so it's restricted to the appropriate users.

Should also note this will affect which workflows can be edited by certain users on the single site admin view.

**Comment by veselala** [comment]
Closing this one as we are dropping Workflows for now.
