### ISSUE TITLE
Add Gmail inbox action support

### ISSUE THREAD

**Issue by johnbillion** [humanmade/Workflows#36]
Gmail supports the specification of actions which appear next to each email in the inbox. It would be handy if Workflows automatically supported these actions based on the message actions.

**Comment by roborourke** [comment]
Documentation for reference: https://developers.google.com/gmail/markup/actions/actions-overview

**Comment by roborourke** [comment]
Ok so not that straight forward. We can add the markup but it's up to the site owner to meet the guidelines specified here which most users won't https://developers.google.com/gmail/markup/registering-with-google

**Comment by roborourke** [comment]
Addendum, will also require us to send email as html, or as mixed html & text.

**Comment by rmccue** [comment]
Closing as this isn't possible.
