### ISSUE TITLE
UI Object

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#4]
The UI object is for defining a set of fields and storing and retrieving the values of which are passed to the destination objects, recipient and event handlers.

It can be used by both the Event and Destination objects.

Protected properties:

- name (string)
- fields (array)
- description (string)
- key (string)
- instances (static array)

Public methods:

* **register (static)**\
  @param $name string\
  @return UI\
  This method will create a new UI object and add it to `self::$instances` with `$name` as the key. It should then return the UI instance.
  
* **constructor**\
  @param $name string A user facing text label for the UI component\
  This should set `$this->name` and call `$this->set_key()` with the `$name` passed through sanitize_key
  
* **set_key**\
  @param $id string An identifier for the UI to store & fetch data against\
  @return self\
  This method should set the value of `$this->key`
  
* **set_description**\
  @param $description string A description of the UI, this should be text to help the user understand the interface\
  @return self\
  This method should set the value of `$this->description`
  
* **add_field**\
  @param $name string The identifier used in the name attribute, will be passed through sanitize_key()\
  @param $label string The user facing text label\
  @param $type string Defaults to ‘text’\
  @param $params array An optional array of custom parameters to configure fields other than text type\
  @return self\
  This method will create an array from the passed parameters with the following keys:
  * `name` - this is used for the input field name
  * `label` - the user facing field label
  * `type` - the type of input. This will depend on
  * `params` - additional field configuration eg. options for a select input
  * `value` - the stored value if any is found via `$this->get_data()`
  This array should be appended to `$this->fields`\
  \
  `$this->fields` is an array of arrays that defines form inputs. They should be understood and output by backbone, mustache or react on the client side. They can have any other arbitrary data associated that may be needed by the front end components to function.\
  \
  **NOTE** Field may be a good candidate for being it’s own type of object but that could happen in a later phase.
  
* **save_data**\
  @param $data array An array of the field values with the field names as the keys\
  @return bool\
  This method should save the data using the key value, this might be implemented in options or post meta.
  
* **get_data**\
  @return array Returns the keyed array of data associated with this UI\
  This method should use the key to retrieve the stored data for the UI. This might be implemented as options or post meta.
  
* **get_config**\
  @return array A configuration object ready for JSON encoding or parsing in PHP to build the form fields\
  This method should return an array with the following structure:
  ```php
  [
    ‘key’ => ‘baz’,
    ‘name’ => ‘foo’,
    ‘description’ => ‘bar’,
    ‘fields’ => [
        [
           ‘name’ => ‘some_field’,
           ‘label’ => ‘My field’,
           ‘type’  => ‘text’,
           ‘value’ => ‘123’
        ],
        [
           ‘name’ => ‘some_other_field’,
           ‘label’ => ‘My other field’,
           ‘type’  => ‘select’,
           ‘options’ => [
               ‘apples’ => ‘Apples’,
               ‘oranges => ‘Oranges’,
           ],
           ‘value’ => ‘456’
        ]
    ]
  ]
  ```

**Comment by pdewouters** [comment]
I'm not sure how this works, if we take the `draft_to_pending` example, I'd register a new `Event` and then call `$event->add_ui()`, but should I pass it a new `UI` object which would receive the checkbox fields for the post types?

**Comment by roborourke** [comment]
> I'm not sure how this works, if we take the draft_to_pending example, I'd register a new Event and then call $event->add_ui(), but should I pass it a new UI object which would receive the checkbox fields for the post types?

The simple draft to pending example would just trigger for all post types. We'll need to register the event by name ahead of time and add the UI with post type picker etc...
