### ISSUE TITLE
Auth callback for the "assignees" meta field prevents saving posts

### ISSUE THREAD

**Issue by goldenapples** [humanmade/Workflows#41]
The auth_callback for the meta "assignees" field uses an incorrect function signature and as a result prevents posts from being saved through the REST API - in Gutenberg, for example.

The auth callback for a meta field should follow the signature:

```
$allowed = apply_filters( "auth_{$object_type}_meta_{$meta_key}", $allowed, $meta_key, $object_id, $user_id, $cap, $caps );
```

**Comment by johnbillion** [comment]
Fixed in #42.
