### ISSUE TITLE
Idea: Zapier destination integration

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#44]
Think this one might be good to bake in.

**Comment by vinnygreen** [comment]
I would love to see this happen! There are a ton of experiments I have in various apps that I could bind to Wordpress data with a Zapier trigger. 

If Altis let us deploy a private Zapier app for my team, it would be a huge productivity boost. My current use case would be syncing WordPress Posts to Jira Issues or Airtable records. 

It is also simple to use Webhooks by Zapier to send data to an endpoint.

**Comment by roborourke** [comment]
Cheers Vinny. It's hard to say when we'll have some dedicated time for this but we can start with some research into the Zapier API.

The webhooks in this plugin are a little limited in the sense that they're `GET` requests and data is passed in the query string. I think we'd need the option for `POST` request webhooks with an OAuth or JWT token as well to send more complex data. I guess that depends on how much info about the posts you're interesting in syncing between platforms.

**Comment by vinnygreen** [comment]
Happy to discuss some time. Snopes may end up building a zapier app for our fact checking needs.

**Comment by vinnygreen** [comment]
We are working on a very simple Zapier webhook destination that passes JSON on status change events:

https://github.com/snopesdotcom/wpcms/pull/2247

**Comment by rmccue** [comment]
Closing out, can track in Productboard instead.
