### ISSUE TITLE
Remove package lock file

### ISSUE THREAD

**Issue by johnbillion** [humanmade/Workflows#58]
The package lock file for Composer shouldn't be committed as this is a library, not a project. Is it needed as part of the build process on CircleCI?

**Comment by roborourke** [comment]
mm no, I thought you were meant to commit all lock files :/

**Comment by paulgibbs** [comment]
These cover my opinion on this well. From https://stackoverflow.com/questions/18901094/composer-lock-in-library

> It won't cause any issue because the composer.lock is only used when you actually run composer install within the library's root directory. When it is installed as a dependency the dependencies' lock files are never taken into account.
> That said, for libraries it indeed does not really make sense to commit a lock file, so feel free to .gitignore it. We just say to always commit it because that is what 99% of the people should do. If some library authors know better and ignore it in their libs that's fine, but it does not really matter either way.

And

> It's worth putting the composer.lock in a library for the same reason that you would put it in deployable projects; to allow you develop and test the library against exactly the same dependencies that were used in it's development.
> 
> This would be useful for your automated testing of libraries, as well as helping to quickly identify whether bugs in the library are caused either by a an actual bug in the library itself, or a bug/changed behaviour in one of it's dependencies. Or to put it more colloquially it help avoids the 'works for me' problem.

**Comment by johnbillion** [comment]
My understanding is that committing a lock file to a library introduces more problems than it solves.

For example, some dependencies resolve differently depending on the PHP version that's in use, because installing on an older version of PHP will result in older dependencies being installed due to later versions having higher PHP version requirements.

This means that if a lock file is in place then a user with an older version of PHP will be prevented from installing the package's dependencies because their version of PHP doesn't meet the requirements, even though they are perfectly able to install the package's dependencies with a fresh install that pulls in dependencies according to their PHP version.

This problem doesn't exist for a composer project where version constraints, dependencies, and the operating environment are tightly controlled.

That said, after a quick bit of Googling it does appear that it comes down to personal preference whether or not you include the lock file in a library.

**Comment by johnbillion** [comment]
Here's an example of a package of mine that broke when I added the lock file to version control: https://travis-ci.org/johnbillion/extended-cpts/builds/269311237

**Comment by roborourke** [comment]
I think I'll remove it for now, then when/if there are dependencies to add we can use exact versions rather than any special semver notations.
