### ISSUE TITLE
Notice on register_rest_route function usage

### ISSUE THREAD

**Issue by dhanendran** [humanmade/Workflows#71]
When I installed this plugin and activated it, I'm seeing a notice on the hook.

> Notice: register_rest_route was called incorrectly. REST API routes must be registered on the rest_api_init action. Please see Debugging in WordPress for more information. (This message was added in version 5.1.0.) in /srv/www/ABC-XYZ/public_html/wp-includes/functions.php on line 4667

This error relates to the hook on the [new-editorial-comment.php](https://github.com/humanmade/Workflows/blob/e72f2a256c71a6f28756e7ce685c1272ea99840d/lib/events/new-editorial-comment.php) file.

https://github.com/humanmade/Workflows/blob/e72f2a256c71a6f28756e7ce685c1272ea99840d/lib/events/new-editorial-comment.php#L279

The callback function `assignees_api` should be hooked into `rest_api_init` instead of `init`.

**Comment by roborourke** [comment]
@dhanendran thanks for using the plugin! I was just about to add this exact issue :)
