### ISSUE TITLE
Can't save a new workflow

### ISSUE THREAD

**Issue by ShinichiNishikawa** [humanmade/Workflows#77]
### Expected and what happens.

I want to save but I get the following error. 

<img width="611" alt="スクリーンショット 2019-05-09 17 34 56" src="https://user-images.githubusercontent.com/1124652/57439912-fa779780-7281-11e9-926c-4dbf197b3504.png">

I see a circling icon next to the "save" button for like 0.1 sec. No error message.

### reproducing

* Setup chassis. I followed https://github.com/humanmade/platform-documentation/tree/master/other-docs/getting-started and https://hmn.slack.com/archives/C3CKS8LLR/p1556893582408100. 
* login and try saving a test workflow at http://platform.local/wp-admin/post-new.php?post_type=hm_workflow

#### data I input

* I tried both Japanese and Latin only and the result seemed the same.
* I chose 
    * a post is a pendig review
    * subject aaa
    * message bbb, 
    * specifc users... admin, 
    * dashboard.

using %title% etc didn't help either. toggling enable button didn't help.

### Other notes

* Permalink setting is post name: http://platform.local/blog/%postname%/

What I suspect is that it's sending a POST req to http://platform.local/wp-json/workflows/v1/workflows/21  but it should be http://platform.local/blog/wp-json/workflows/v1/workflows/21

**Comment by ShinichiNishikawa** [comment]
When I change the "Who should be notified?" to "All users," I could save it.

**Comment by roborourke** [comment]
So possibly a problem with permalinks or with the user selection drop down. I’ll take a look.

**Comment by roborourke** [comment]
Error is `recipients: "recipients[0][value][0] is not of type string."` - this should show up however. Should be straight forward to fix
