### ISSUE TITLE
Built in Event: Draft to Pending

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#8]
- [ ] UI has a checkbox list of post types
- [ ] Adds a custom field to post edit screen for ‘Assignee’ (or owner)
- [ ] Has a recipient handler called ‘Post assignee’ that gets the user ID from post meta

**Comment by pdewouters** [comment]
@roborourke what is the Assignee field for?

**Comment by pdewouters** [comment]
In the code how would you define for which post types the action needs to run?

**Comment by roborourke** [comment]
@pdewouters 

> What is the Assignee field for?
Assignee field would be the person responsible for the post, say an editor, it's to be able to notify someone other than the post author

> In the code how would you define for which post types the action needs to run?
That would be handled via the UI data which would get passed through to the event listener, the event listener will have the info from the action eg. the post object and then the logic to handle the settings from the UI would be handled in the event listener to select the post type.
