### ISSUE TITLE
Line breaks in the Dashboard notification is converted to "n"

### ISSUE THREAD

**Issue by ShinichiNishikawa** [humanmade/Workflows#81]
When I have the following setting, 

![スクリーンショット 2019-05-13 23 15 19](https://user-images.githubusercontent.com/1124652/57628639-4d7c8200-75d5-11e9-983a-2af595faa697.png)

the notification on the dashboard appears as below

![スクリーンショット 2019-05-13 23 14 48](https://user-images.githubusercontent.com/1124652/57628681-5d946180-75d5-11e9-83f7-3aa974d1d22b.png)

**Comment by roborourke** [comment]
Oof! Cheers for the bug report

**Comment by dashaluna** [comment]
I'm also seeing special chars encoding in the dashboard notifications.

**Comment by roborourke** [comment]
Fixed in 0.3.4, you can [grab the zip here](https://github.com/humanmade/Workflows/archive/0.3.4.zip)

The version in Altis will be updated this week.
