### ISSUE TITLE
Special chars in a post title for a new comment are not displayed correctly.

### ISSUE THREAD

**Issue by dashaluna** [humanmade/Workflows#84]
Special chars most likely are being escaped via `add_filter( 'the_title', 'convert_chars' );` that's applied for `get_the_title` here https://github.com/humanmade/Workflows/blob/master/lib/events/new-comment.php#L40

**Comment by roborourke** [comment]
Fixed in #85 

Cheers @dashaluna 👍

**Comment by roborourke** [comment]
Release 0.3.5 contains the fix
