### ISSUE TITLE
Replace dashboard notification storage with post type

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#89]
This would make user notifications in the dashboard much easier to reason about. They're kind of an advanced notification compared to emails and could have more useful features such as:

- mark as read / statuses
- notification types (taxonomy)
- notification groups
- faster & more granular lookups / querying
  - better db usage
- easier to clean up old notifications

Props to @fklein-lu for the suggestion.

**Comment by rmccue** [comment]
Closing as stale.
