### ISSUE TITLE
Enhance `who` filtering

### ISSUE THREAD

**Issue by dashaluna** [humanmade/Workflows#92]
Scenario:

There is a single `Event` let's say `published_comment`.
There are two `Workflow` registered for them, so that the users can be notified on the `dashboard` and via `email`.

The users for both `Workflow`s are the same, except that users to be sent emails to are further filtered by a custom function/data.

Is it possible to define recipients for an `Event` once, but then filter them further out differently per each `Workflow`.

Hope that makes sense :)

**Comment by rmccue** [comment]
Closing as stale, we can handle in Productboard.
